
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.2'
version_full = 'ad8c61d00fb7d2474d129a5bb553dd0f5206f279'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
