
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.0'
version_full = 'dd9bd6219f7187e7ddf26aa740a1d3ff00910e0f'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
